### ISSUE TITLE
GEXF export error - no attributes

### ISSUE THREAD

**Issue by mikima** [densitydesign/strumentalia-seealsology#3]
In the GEXF, variables type are not declared.
The file should contain this line:
```
<attributes class="node">
<attribute id="level" title="Level" type="integer"/>
</attributes>
```

**Comment by Yomguithereal** [comment]
Can you check whether those attributes would be defined at the end of the xml file maybe? If this is the case, you should update to the latest version of the gexf library.

**Comment by boogheta** [comment]
apparently fixed now
