### ISSUE TITLE
wikipedia url are broken

### ISSUE THREAD

**Issue by mmdelc** [densitydesign/strumentalia-seealsology#31]
When you paste the wikipedia link in the box, it doesn't work. Only redirect to https://en.wikipedia.org/wiki/Org 
The tool is useful for my classes, is there any way that you can please take a look? Thanks.

**Comment by boogheta** [comment]
Hello and thanks a lot for the report!
It looks like a "fix" I pushed earlier this summer actually introduced this new bug I didn't notice.
I've just corrected it thanks to your feedback!
