### ISSUE TITLE
Tool not working for English Wikipedia

### ISSUE THREAD

**Issue by tommv** [densitydesign/strumentalia-seealsology#37]
Hi médialab/Density friends,
Just want to signal that the tool seems to have stop working for English Wikipedia (French Wikipedia still works though).

For example, if given https://en.wikipedia.org/wiki/Anthropocene
(which has 7 see also links, non of which containing stop words - https://en.wikipedia.org/wiki/Anthropocene#See_also)
the tool returns "Warning: no result found from these seeds"

https://fr.wikipedia.org/wiki/Anthropoc%C3%A8ne, on the other hand, works perfectly.

Thank you
Tommaso

**Comment by boogheta** [comment]
It seems like there are some changes in WP's API that need to be followed on, will check on that later.
For future ref:
```
{
    "batchcomplete": "",
    "warnings": {
        "main": {
            "*": "Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application."
        },
        "revisions": {
            "*": "Because \"rvslots\" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used."
        }
    },
    "query": {
        "pages": {
            "374390": {
                "pageid": 374390,
                "ns": 0,
                "title": "Anthropocene",
                "revisions": [{
                    "contentformat": "text/x-wiki",
                    "contentmodel": "wikitext",
                    "*": "== See also ==\n* {{Annotated link|Anthropogenic biomes}}e\n* {{Annotated link|Holocene extinction}}\n* {{Annotated link|Human overpopulation}}\n* {{Annotated link|Meghalayan}}\n* {{Annotated link|Novel ecosystem}}\n* {{Annotated link|Overconsumption}}\n* {{Annotated link|Planetary boundaries}}"
                }]
            }
        }
    }
}
```

**Comment by boogheta** [comment]
Well actually the problem was rather the format of the links in the See Also section of this specific page: it uses the {{Annotated link|PAGENAME}} instead of the classical [[PAGENAME]] syntax, which might be new. I added a way to handle those which fixed this specific case!

**Comment by tommv** [comment]
Thank you, works perfectly now !
