### ISSUE TITLE
GEXF export error - Network should be directed by defalut

### ISSUE THREAD

**Issue by mikima** [densitydesign/strumentalia-seealsology#4]
The network should be directed.
It can be stated changing this node in the resulting GEXF file:
```
<graph defaultedgetype="directed">
```

**Comment by Yomguithereal** [comment]
Just change [this line](https://github.com/densitydesign/strumentalia-seealsology/blob/master/app/scripts/controllers/alt.js#L212) into the following and you should be good to go:

```js
var gexfDoc = gexf.create({defaultEdgeType: 'directed'});
```

**Comment by mikima** [comment]
Thanks!
