### ISSUE TITLE
Need this tool for Tamil Wikipedia

### ISSUE THREAD

**Issue by Sibicoder** [densitydesign/strumentalia-seealsology#7]
I would like to use this tool for Tamil wikipedia. I can contribute if anything is possible from my side. Kindly help me to extend its feature. :)

**Comment by Yomguithereal** [comment]
Hello @Sibicoder. If I remember correctly, to add a language, you just need to edit [this](https://github.com/densitydesign/strumentalia-seealsology/blob/master/app/scripts/controllers/alt.js#L6-L41) part of the code. You can try that on your end and when you are happy with the result, you can file a pull request to the repository.

**Comment by boogheta** [comment]
If you are not a coder, you can do so by clicking the little pen in the top right corner of the page linked by @yomguithereal and edit the file in your browser. We'll review your changes and let you know if something is wrong or missing.
Thanks!

**Comment by Sibicoder** [comment]
@boogheta  Thanks for the help :) I have modified the file. Kindly let me know if anything is wrong or once the change has been updated. Thanks once again.

**Comment by boogheta** [comment]
merged, thx
